set nocompatible
filetype off 

" Add fuzzy finder to runtimepath
set rtp+=/usr/local/opt/fzf
nnoremap <silent> <C-p> :FZF<CR>

" Softabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

set noswapfile
set dir=~/.tmp

set splitbelow
set splitright

set hlsearch
hi Search ctermbg=LightGreen
hi Search ctermfg=Black

set number
autocmd FileType gitcommit set textwidth=72
autocmd FileType gitcommit set colorcolumn=73
set colorcolumn=101

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Commands
command Json %! python -m json.tool
command Rspec ! bundle exec rspec

" Vim test
" See: https://github.com/vim-test/vim-test#setup
nmap <silent> <C-t> :TestNearest<CR>
